# Script for populating the database. You can run it as:
#
#     mix run priv/repo/seeds.exs
#
# Inside the script, you can read and write to any of your
# repositories directly:
#
#     CrowdReview.Repo.insert!(%CrowdReview.SomeSchema{})
#
# We recommend using the bang functions (`insert!`, `update!`
# and so on) as they will fail if something goes wrong.
alias CrowdReview.{Language, Repo}

languages = [
  %{name: "ActionScript"},
  %{name: "C"},
  %{name: "C#"},
  %{name: "C++"},
  %{name: "Clojure"},
  %{name: "CoffeeScript"},
  %{name: "CSS"},
  %{name: "Go"},
  %{name: "Haskell"},
  %{name: "HTML"},
  %{name: "Java"},
  %{name: "JavaScript"},
  %{name: "Lua"},
  %{name: "MATLAB"},
  %{name: "Objective-C"},
  %{name: "Perl"},
  %{name: "PHP"},
  %{name: "Python"},
  %{name: "R"},
  %{name: "Ruby"},
  %{name: "Scala"},
  %{name: "Shell"},
  %{name: "Swift"},
  %{name: "TeX"},
  %{name: "Vim script"},
  %{name: "1C Enterprise"},
  %{name: "ABAP"},
  %{name: "ABNF"},
  %{name: "Ada"},
  %{name: "Adobe Font Metrics"},
  %{name: "Agda"},
  %{name: "AGS Script"},
  %{name: "Alloy"},
  %{name: "Alpine Abuild"},
  %{name: "AMPL"},
  %{name: "AngelScript"},
  %{name: "Ant Build System"},
  %{name: "ANTLR"},
  %{name: "ApacheConf"},
  %{name: "Apex"},
  %{name: "API Blueprint"},
  %{name: "APL"},
  %{name: "Apollo Guidance Computer"},
  %{name: "AppleScript"},
  %{name: "Arc"},
  %{name: "AsciiDoc"},
  %{name: "ASN.1"},
  %{name: "ASP"},
  %{name: "AspectJ"},
  %{name: "Assembly"},
  %{name: "Asymptote"},
  %{name: "ATS"},
  %{name: "Augeas"},
  %{name: "AutoHotkey"},
  %{name: "AutoIt"},
  %{name: "Awk"},
  %{name: "Ballerina"},
  %{name: "Batchfile"},
  %{name: "Befunge"},
  %{name: "Bison"},
  %{name: "BitBake"},
  %{name: "Blade"},
  %{name: "BlitzBasic"},
  %{name: "BlitzMax"},
  %{name: "Bluespec"},
  %{name: "Boo"},
  %{name: "Brainfuck"},
  %{name: "Brightscript"},
  %{name: "Bro"},
  %{name: "C-ObjDump"},
  %{name: "C2hs Haskell"},
  %{name: "Cabal Config"},
  %{name: "Cap'n Proto"},
  %{name: "CartoCSS"},
  %{name: "Ceylon"},
  %{name: "Chapel"},
  %{name: "Charity"},
  %{name: "ChucK"},
  %{name: "Cirru"},
  %{name: "Clarion"},
  %{name: "Clean"},
  %{name: "Click"},
  %{name: "CLIPS"},
  %{name: "Closure Templates"},
  %{name: "Cloud Firestore Security Rules"},
  %{name: "CMake"},
  %{name: "COBOL"},
  %{name: "ColdFusion"},
  %{name: "ColdFusion CFC"},
  %{name: "COLLADA"},
  %{name: "Common Lisp"},
  %{name: "Common Workflow Language"},
  %{name: "Component Pascal"},
  %{name: "CoNLL-U"},
  %{name: "Cool"},
  %{name: "Coq"},
  %{name: "Cpp-ObjDump"},
  %{name: "Creole"},
  %{name: "Crystal"},
  %{name: "CSON"},
  %{name: "Csound"},
  %{name: "Csound Document"},
  %{name: "Csound Score"},
  %{name: "CSV"},
  %{name: "Cuda"},
  %{name: "CWeb"},
  %{name: "Cycript"},
  %{name: "Cython"},
  %{name: "D"},
  %{name: "D-ObjDump"},
  %{name: "Darcs Patch"},
  %{name: "Dart"},
  %{name: "DataWeave"},
  %{name: "desktop"},
  %{name: "Diff"},
  %{name: "DIGITAL Command Language"},
  %{name: "DM"},
  %{name: "DNS Zone"},
  %{name: "Dockerfile"},
  %{name: "Dogescript"},
  %{name: "DTrace"},
  %{name: "Dylan"},
  %{name: "E"},
  %{name: "Eagle"},
  %{name: "Easybuild"},
  %{name: "EBNF"},
  %{name: "eC"},
  %{name: "Ecere Projects"},
  %{name: "ECL"},
  %{name: "ECLiPSe"},
  %{name: "EditorConfig"},
  %{name: "Edje Data Collection"},
  %{name: "edn"},
  %{name: "Eiffel"},
  %{name: "EJS"},
  %{name: "Elixir"},
  %{name: "Elm"},
  %{name: "Emacs Lisp"},
  %{name: "EmberScript"},
  %{name: "EML"},
  %{name: "EQ"},
  %{name: "Erlang"},
  %{name: "F#"},
  %{name: "F*"},
  %{name: "Factor"},
  %{name: "Fancy"},
  %{name: "Fantom"},
  %{name: "FIGlet Font"},
  %{name: "Filebench WML"},
  %{name: "Filterscript"},
  %{name: "fish"},
  %{name: "FLUX"},
  %{name: "Formatted"},
  %{name: "Forth"},
  %{name: "Fortran"},
  %{name: "FreeMarker"},
  %{name: "Frege"},
  %{name: "G-code"},
  %{name: "Game Maker Language"},
  %{name: "GAMS"},
  %{name: "GAP"},
  %{name: "GCC Machine Description"},
  %{name: "GDB"},
  %{name: "GDScript"},
  %{name: "Genie"},
  %{name: "Genshi"},
  %{name: "Gentoo Ebuild"},
  %{name: "Gentoo Eclass"},
  %{name: "Gerber Image"},
  %{name: "Gettext Catalog"},
  %{name: "Gherkin"},
  %{name: "Git Attributes"},
  %{name: "Git Config"},
  %{name: "GLSL"},
  %{name: "Glyph"},
  %{name: "Glyph Bitmap Distribution Format"},
  %{name: "GN"},
  %{name: "Gnuplot"},
  %{name: "Golo"},
  %{name: "Gosu"},
  %{name: "Grace"},
  %{name: "Gradle"},
  %{name: "Grammatical Framework"},
  %{name: "Graph Modeling Language"},
  %{name: "GraphQL"},
  %{name: "Graphviz (DOT)"},
  %{name: "Groovy"},
  %{name: "Groovy Server Pages"},
  %{name: "Hack"},
  %{name: "Haml"},
  %{name: "Handlebars"},
  %{name: "HAProxy"},
  %{name: "Harbour"},
  %{name: "Haxe"},
  %{name: "HCL"},
  %{name: "HiveQL"},
  %{name: "HLSL"},
  %{name: "HTML+Django"},
  %{name: "HTML+ECR"},
  %{name: "HTML+EEX"},
  %{name: "HTML+ERB"},
  %{name: "HTML+PHP"},
  %{name: "HTML+Razor"},
  %{name: "HTTP"},
  %{name: "HXML"},
  %{name: "Hy"},
  %{name: "HyPhy"},
  %{name: "IDL"},
  %{name: "Idris"},
  %{name: "Ignore List"},
  %{name: "IGOR Pro"},
  %{name: "Inform 7"},
  %{name: "INI"},
  %{name: "Inno Setup"},
  %{name: "Io"},
  %{name: "Ioke"},
  %{name: "IRC log"},
  %{name: "Isabelle"},
  %{name: "Isabelle ROOT"},
  %{name: "J"},
  %{name: "Jasmin"},
  %{name: "Java Properties"},
  %{name: "Java Server Pages"},
  %{name: "JFlex"},
  %{name: "Jison"},
  %{name: "Jison Lex"},
  %{name: "Jolie"},
  %{name: "JSON"},
  %{name: "JSON with Comments"},
  %{name: "JSON5"},
  %{name: "JSONiq"},
  %{name: "JSONLD"},
  %{name: "Jsonnet"},
  %{name: "JSX"},
  %{name: "Julia"},
  %{name: "Jupyter Notebook"},
  %{name: "KiCad Layout"},
  %{name: "KiCad Legacy Layout"},
  %{name: "KiCad Schematic"},
  %{name: "Kit"},
  %{name: "Kotlin"},
  %{name: "KRL"},
  %{name: "LabVIEW"},
  %{name: "Lasso"},
  %{name: "Latte"},
  %{name: "Lean"},
  %{name: "Less"},
  %{name: "Lex"},
  %{name: "LFE"},
  %{name: "LilyPond"},
  %{name: "Limbo"},
  %{name: "Linker Script"},
  %{name: "Linux Kernel Module"},
  %{name: "Liquid"},
  %{name: "Literate Agda"},
  %{name: "Literate CoffeeScript"},
  %{name: "Literate Haskell"},
  %{name: "LiveScript"},
  %{name: "LLVM"},
  %{name: "Logos"},
  %{name: "Logtalk"},
  %{name: "LOLCODE"},
  %{name: "LookML"},
  %{name: "LoomScript"},
  %{name: "LSL"},
  %{name: "LTspice Symbol"},
  %{name: "M"},
  %{name: "M4"},
  %{name: "M4Sugar"},
  %{name: "Makefile"},
  %{name: "Mako"},
  %{name: "Markdown"},
  %{name: "Marko"},
  %{name: "Mask"},
  %{name: "Mathematica"},
  %{name: "Maven POM"},
  %{name: "Max"},
  %{name: "MAXScript"},
  %{name: "mcfunction"},
  %{name: "MediaWiki"},
  %{name: "Mercury"},
  %{name: "Meson"},
  %{name: "Metal"},
  %{name: "MiniD"},
  %{name: "Mirah"},
  %{name: "Modelica"},
  %{name: "Modula-2"},
  %{name: "Modula-3"},
  %{name: "Module Management System"},
  %{name: "Monkey"},
  %{name: "Moocode"},
  %{name: "MoonScript"},
  %{name: "MQL4"},
  %{name: "MQL5"},
  %{name: "MTML"},
  %{name: "MUF"},
  %{name: "mupad"},
  %{name: "Myghty"},
  %{name: "nanorc"},
  %{name: "NCL"},
  %{name: "Nearley"},
  %{name: "Nemerle"},
  %{name: "nesC"},
  %{name: "NetLinx"},
  %{name: "NetLinx+ERB"},
  %{name: "NetLogo"},
  %{name: "NewLisp"},
  %{name: "Nextflow"},
  %{name: "Nginx"},
  %{name: "Nim"},
  %{name: "Ninja"},
  %{name: "Nit"},
  %{name: "Nix"},
  %{name: "NL"},
  %{name: "NSIS"},
  %{name: "Nu"},
  %{name: "NumPy"},
  %{name: "ObjDump"},
  %{name: "Objective-C++"},
  %{name: "Objective-J"},
  %{name: "OCaml"},
  %{name: "Omgrofl"},
  %{name: "ooc"},
  %{name: "Opa"},
  %{name: "Opal"},
  %{name: "OpenCL"},
  %{name: "OpenEdge ABL"},
  %{name: "OpenRC runscript"},
  %{name: "OpenSCAD"},
  %{name: "OpenType Feature File"},
  %{name: "Org"},
  %{name: "Ox"},
  %{name: "Oxygene"},
  %{name: "Oz"},
  %{name: "P4"},
  %{name: "Pan"},
  %{name: "Papyrus"},
  %{name: "Parrot"},
  %{name: "Parrot Assembly"},
  %{name: "Parrot Internal Representation"},
  %{name: "Pascal"},
  %{name: "Pawn"},
  %{name: "Pep8"},
  %{name: "Perl 6"},
  %{name: "Pic"},
  %{name: "Pickle"},
  %{name: "PicoLisp"},
  %{name: "PigLatin"},
  %{name: "Pike"},
  %{name: "PLpgSQL"},
  %{name: "PLSQL"},
  %{name: "Pod"},
  %{name: "Pod 6"},
  %{name: "PogoScript"},
  %{name: "Pony"},
  %{name: "PostCSS"},
  %{name: "PostScript"},
  %{name: "POV-Ray SDL"},
  %{name: "PowerBuilder"},
  %{name: "PowerShell"},
  %{name: "Processing"},
  %{name: "Prolog"},
  %{name: "Propeller Spin"},
  %{name: "Protocol Buffer"},
  %{name: "Public Key"},
  %{name: "Pug"},
  %{name: "Puppet"},
  %{name: "Pure Data"},
  %{name: "PureBasic"},
  %{name: "PureScript"},
  %{name: "Python console"},
  %{name: "Python traceback"},
  %{name: "q"},
  %{name: "QMake"},
  %{name: "QML"},
  %{name: "Quake"},
  %{name: "Racket"},
  %{name: "Ragel"},
  %{name: "RAML"},
  %{name: "Rascal"},
  %{name: "Raw token data"},
  %{name: "RDoc"},
  %{name: "REALbasic"},
  %{name: "Reason"},
  %{name: "Rebol"},
  %{name: "Red"},
  %{name: "Redcode"},
  %{name: "Regular Expression"},
  %{name: "Ren'Py"},
  %{name: "RenderScript"},
  %{name: "reStructuredText"},
  %{name: "REXX"},
  %{name: "RHTML"},
  %{name: "Rich Text Format"},
  %{name: "Ring"},
  %{name: "RMarkdown"},
  %{name: "RobotFramework"},
  %{name: "Roff"},
  %{name: "Roff Manpage"},
  %{name: "Rouge"},
  %{name: "RPC"},
  %{name: "RPM Spec"},
  %{name: "RUNOFF"},
  %{name: "Rust"},
  %{name: "Sage"},
  %{name: "SaltStack"},
  %{name: "SAS"},
  %{name: "Sass"},
  %{name: "Scaml"},
  %{name: "Scheme"},
  %{name: "Scilab"},
  %{name: "SCSS"},
  %{name: "sed"},
  %{name: "Self"},
  %{name: "ShaderLab"},
  %{name: "ShellSession"},
  %{name: "Shen"},
  %{name: "Slash"},
  %{name: "Slice"},
  %{name: "Slim"},
  %{name: "Smali"},
  %{name: "Smalltalk"},
  %{name: "Smarty"},
  %{name: "SMT"},
  %{name: "Solidity"},
  %{name: "SourcePawn"},
  %{name: "SPARQL"},
  %{name: "Spline Font Database"},
  %{name: "SQF"},
  %{name: "SQL"},
  %{name: "SQLPL"},
  %{name: "Squirrel"},
  %{name: "SRecode Template"},
  %{name: "Stan"},
  %{name: "Standard ML"},
  %{name: "Stata"},
  %{name: "STON"},
  %{name: "Stylus"},
  %{name: "SubRip Text"},
  %{name: "SugarSS"},
  %{name: "SuperCollider"},
  %{name: "SVG"},
  %{name: "SystemVerilog"},
  %{name: "Tcl"},
  %{name: "Tcsh"},
  %{name: "Tea"},
  %{name: "Terra"},
  %{name: "Text"},
  %{name: "Textile"},
  %{name: "Thrift"},
  %{name: "TI Program"},
  %{name: "TLA"},
  %{name: "TOML"},
  %{name: "Turing"},
  %{name: "Turtle"},
  %{name: "Twig"},
  %{name: "TXL"},
  %{name: "Type Language"},
  %{name: "TypeScript"},
  %{name: "Unified Parallel C"},
  %{name: "Unity3D Asset"},
  %{name: "Unix Assembly"},
  %{name: "Uno"},
  %{name: "UnrealScript"},
  %{name: "UrWeb"},
  %{name: "Vala"},
  %{name: "VCL"},
  %{name: "Verilog"},
  %{name: "VHDL"},
  %{name: "Visual Basic"},
  %{name: "Volt"},
  %{name: "Vue"},
  %{name: "Wavefront Material"},
  %{name: "Wavefront Object"},
  %{name: "wdl"},
  %{name: "Web Ontology Language"},
  %{name: "WebAssembly"},
  %{name: "WebIDL"},
  %{name: "Windows Registry Entries"},
  %{name: "wisp"},
  %{name: "World of Warcraft Addon Data"},
  %{name: "X BitMap"},
  %{name: "X Font Directory Index"},
  %{name: "X PixMap"},
  %{name: "X10"},
  %{name: "xBase"},
  %{name: "XC"},
  %{name: "XCompose"},
  %{name: "XML"},
  %{name: "Xojo"},
  %{name: "XPages"},
  %{name: "XProc"},
  %{name: "XQuery"},
  %{name: "XS"},
  %{name: "XSLT"},
  %{name: "Xtend"},
  %{name: "Yacc"},
  %{name: "YAML"},
  %{name: "YANG"},
  %{name: "YARA"},
  %{name: "YASnippet"},
  %{name: "ZAP"},
  %{name: "Zephir"},
  %{name: "Zig"},
  %{name: "ZIL"},
  %{name: "Zimpl"}
]

Enum.each(languages, fn language_attrs ->
  found_language = Repo.get_by(Language, name: language_attrs.name)

  if(found_language == nil) do
    changeset = Language.changeset(%Language{}, language_attrs)
    Repo.insert!(changeset)
  end
end)
