# Script for populating the database. You can run it as:
#
#     mix run priv/repo/seeds.exs
#
# Inside the script, you can read and write to any of your
# repositories directly:
#
#     CrowdReview.Repo.insert!(%CrowdReview.SomeSchema{})
#
# We recommend using the bang functions (`insert!`, `update!`
# and so on) as they will fail if something goes wrong.
alias CrowdReview.{Language, Repo}

languages = [
  %Language{name: "ActionScript"},
  %Language{name: "C"},
  %Language{name: "C#"},
  %Language{name: "C++"},
  %Language{name: "Clojure"},
  %Language{name: "CoffeeScript"},
  %Language{name: "CSS"},
  %Language{name: "Go"},
  %Language{name: "Haskell"},
  %Language{name: "HTML"},
  %Language{name: "Java"},
  %Language{name: "JavaScript"},
  %Language{name: "Lua"},
  %Language{name: "MATLAB"},
  %Language{name: "Objective-C"},
  %Language{name: "Perl"},
  %Language{name: "PHP"},
  %Language{name: "Python"},
  %Language{name: "R"},
  %Language{name: "Ruby"},
  %Language{name: "Scala"},
  %Language{name: "Shell"},
  %Language{name: "Swift"},
  %Language{name: "TeX"},
  %Language{name: "Vim script"},
  %Language{name: "1C Enterprise"},
  %Language{name: "ABAP"},
  %Language{name: "ABNF"},
  %Language{name: "Ada"},
  %Language{name: "Adobe Font Metrics"},
  %Language{name: "Agda"},
  %Language{name: "AGS Script"},
  %Language{name: "Alloy"},
  %Language{name: "Alpine Abuild"},
  %Language{name: "AMPL"},
  %Language{name: "AngelScript"},
  %Language{name: "Ant Build System"},
  %Language{name: "ANTLR"},
  %Language{name: "ApacheConf"},
  %Language{name: "Apex"},
  %Language{name: "API Blueprint"},
  %Language{name: "APL"},
  %Language{name: "Apollo Guidance Computer"},
  %Language{name: "AppleScript"},
  %Language{name: "Arc"},
  %Language{name: "AsciiDoc"},
  %Language{name: "ASN.1"},
  %Language{name: "ASP"},
  %Language{name: "AspectJ"},
  %Language{name: "Assembly"},
  %Language{name: "Asymptote"},
  %Language{name: "ATS"},
  %Language{name: "Augeas"},
  %Language{name: "AutoHotkey"},
  %Language{name: "AutoIt"},
  %Language{name: "Awk"},
  %Language{name: "Ballerina"},
  %Language{name: "Batchfile"},
  %Language{name: "Befunge"},
  %Language{name: "Bison"},
  %Language{name: "BitBake"},
  %Language{name: "Blade"},
  %Language{name: "BlitzBasic"},
  %Language{name: "BlitzMax"},
  %Language{name: "Bluespec"},
  %Language{name: "Boo"},
  %Language{name: "Brainfuck"},
  %Language{name: "Brightscript"},
  %Language{name: "Bro"},
  %Language{name: "C-ObjDump"},
  %Language{name: "C2hs Haskell"},
  %Language{name: "Cabal Config"},
  %Language{name: "Cap'n Proto"},
  %Language{name: "CartoCSS"},
  %Language{name: "Ceylon"},
  %Language{name: "Chapel"},
  %Language{name: "Charity"},
  %Language{name: "ChucK"},
  %Language{name: "Cirru"},
  %Language{name: "Clarion"},
  %Language{name: "Clean"},
  %Language{name: "Click"},
  %Language{name: "CLIPS"},
  %Language{name: "Closure Templates"},
  %Language{name: "Cloud Firestore Security Rules"},
  %Language{name: "CMake"},
  %Language{name: "COBOL"},
  %Language{name: "ColdFusion"},
  %Language{name: "ColdFusion CFC"},
  %Language{name: "COLLADA"},
  %Language{name: "Common Lisp"},
  %Language{name: "Common Workflow Language"},
  %Language{name: "Component Pascal"},
  %Language{name: "CoNLL-U"},
  %Language{name: "Cool"},
  %Language{name: "Coq"},
  %Language{name: "Cpp-ObjDump"},
  %Language{name: "Creole"},
  %Language{name: "Crystal"},
  %Language{name: "CSON"},
  %Language{name: "Csound"},
  %Language{name: "Csound Document"},
  %Language{name: "Csound Score"},
  %Language{name: "CSV"},
  %Language{name: "Cuda"},
  %Language{name: "CWeb"},
  %Language{name: "Cycript"},
  %Language{name: "Cython"},
  %Language{name: "D"},
  %Language{name: "D-ObjDump"},
  %Language{name: "Darcs Patch"},
  %Language{name: "Dart"},
  %Language{name: "DataWeave"},
  %Language{name: "desktop"},
  %Language{name: "Diff"},
  %Language{name: "DIGITAL Command Language"},
  %Language{name: "DM"},
  %Language{name: "DNS Zone"},
  %Language{name: "Dockerfile"},
  %Language{name: "Dogescript"},
  %Language{name: "DTrace"},
  %Language{name: "Dylan"},
  %Language{name: "E"},
  %Language{name: "Eagle"},
  %Language{name: "Easybuild"},
  %Language{name: "EBNF"},
  %Language{name: "eC"},
  %Language{name: "Ecere Projects"},
  %Language{name: "ECL"},
  %Language{name: "ECLiPSe"},
  %Language{name: "EditorConfig"},
  %Language{name: "Edje Data Collection"},
  %Language{name: "edn"},
  %Language{name: "Eiffel"},
  %Language{name: "EJS"},
  %Language{name: "Elixir"},
  %Language{name: "Elm"},
  %Language{name: "Emacs Lisp"},
  %Language{name: "EmberScript"},
  %Language{name: "EML"},
  %Language{name: "EQ"},
  %Language{name: "Erlang"},
  %Language{name: "F#"},
  %Language{name: "F*"},
  %Language{name: "Factor"},
  %Language{name: "Fancy"},
  %Language{name: "Fantom"},
  %Language{name: "FIGlet Font"},
  %Language{name: "Filebench WML"},
  %Language{name: "Filterscript"},
  %Language{name: "fish"},
  %Language{name: "FLUX"},
  %Language{name: "Formatted"},
  %Language{name: "Forth"},
  %Language{name: "Fortran"},
  %Language{name: "FreeMarker"},
  %Language{name: "Frege"},
  %Language{name: "G-code"},
  %Language{name: "Game Maker Language"},
  %Language{name: "GAMS"},
  %Language{name: "GAP"},
  %Language{name: "GCC Machine Description"},
  %Language{name: "GDB"},
  %Language{name: "GDScript"},
  %Language{name: "Genie"},
  %Language{name: "Genshi"},
  %Language{name: "Gentoo Ebuild"},
  %Language{name: "Gentoo Eclass"},
  %Language{name: "Gerber Image"},
  %Language{name: "Gettext Catalog"},
  %Language{name: "Gherkin"},
  %Language{name: "Git Attributes"},
  %Language{name: "Git Config"},
  %Language{name: "GLSL"},
  %Language{name: "Glyph"},
  %Language{name: "Glyph Bitmap Distribution Format"},
  %Language{name: "GN"},
  %Language{name: "Gnuplot"},
  %Language{name: "Golo"},
  %Language{name: "Gosu"},
  %Language{name: "Grace"},
  %Language{name: "Gradle"},
  %Language{name: "Grammatical Framework"},
  %Language{name: "Graph Modeling Language"},
  %Language{name: "GraphQL"},
  %Language{name: "Graphviz (DOT)"},
  %Language{name: "Groovy"},
  %Language{name: "Groovy Server Pages"},
  %Language{name: "Hack"},
  %Language{name: "Haml"},
  %Language{name: "Handlebars"},
  %Language{name: "HAProxy"},
  %Language{name: "Harbour"},
  %Language{name: "Haxe"},
  %Language{name: "HCL"},
  %Language{name: "HiveQL"},
  %Language{name: "HLSL"},
  %Language{name: "HTML+Django"},
  %Language{name: "HTML+ECR"},
  %Language{name: "HTML+EEX"},
  %Language{name: "HTML+ERB"},
  %Language{name: "HTML+PHP"},
  %Language{name: "HTML+Razor"},
  %Language{name: "HTTP"},
  %Language{name: "HXML"},
  %Language{name: "Hy"},
  %Language{name: "HyPhy"},
  %Language{name: "IDL"},
  %Language{name: "Idris"},
  %Language{name: "Ignore List"},
  %Language{name: "IGOR Pro"},
  %Language{name: "Inform 7"},
  %Language{name: "INI"},
  %Language{name: "Inno Setup"},
  %Language{name: "Io"},
  %Language{name: "Ioke"},
  %Language{name: "IRC log"},
  %Language{name: "Isabelle"},
  %Language{name: "Isabelle ROOT"},
  %Language{name: "J"},
  %Language{name: "Jasmin"},
  %Language{name: "Java Properties"},
  %Language{name: "Java Server Pages"},
  %Language{name: "JFlex"},
  %Language{name: "Jison"},
  %Language{name: "Jison Lex"},
  %Language{name: "Jolie"},
  %Language{name: "JSON"},
  %Language{name: "JSON with Comments"},
  %Language{name: "JSON5"},
  %Language{name: "JSONiq"},
  %Language{name: "JSONLD"},
  %Language{name: "Jsonnet"},
  %Language{name: "JSX"},
  %Language{name: "Julia"},
  %Language{name: "Jupyter Notebook"},
  %Language{name: "KiCad Layout"},
  %Language{name: "KiCad Legacy Layout"},
  %Language{name: "KiCad Schematic"},
  %Language{name: "Kit"},
  %Language{name: "Kotlin"},
  %Language{name: "KRL"},
  %Language{name: "LabVIEW"},
  %Language{name: "Lasso"},
  %Language{name: "Latte"},
  %Language{name: "Lean"},
  %Language{name: "Less"},
  %Language{name: "Lex"},
  %Language{name: "LFE"},
  %Language{name: "LilyPond"},
  %Language{name: "Limbo"},
  %Language{name: "Linker Script"},
  %Language{name: "Linux Kernel Module"},
  %Language{name: "Liquid"},
  %Language{name: "Literate Agda"},
  %Language{name: "Literate CoffeeScript"},
  %Language{name: "Literate Haskell"},
  %Language{name: "LiveScript"},
  %Language{name: "LLVM"},
  %Language{name: "Logos"},
  %Language{name: "Logtalk"},
  %Language{name: "LOLCODE"},
  %Language{name: "LookML"},
  %Language{name: "LoomScript"},
  %Language{name: "LSL"},
  %Language{name: "LTspice Symbol"},
  %Language{name: "M"},
  %Language{name: "M4"},
  %Language{name: "M4Sugar"},
  %Language{name: "Makefile"},
  %Language{name: "Mako"},
  %Language{name: "Markdown"},
  %Language{name: "Marko"},
  %Language{name: "Mask"},
  %Language{name: "Mathematica"},
  %Language{name: "Maven POM"},
  %Language{name: "Max"},
  %Language{name: "MAXScript"},
  %Language{name: "mcfunction"},
  %Language{name: "MediaWiki"},
  %Language{name: "Mercury"},
  %Language{name: "Meson"},
  %Language{name: "Metal"},
  %Language{name: "MiniD"},
  %Language{name: "Mirah"},
  %Language{name: "Modelica"},
  %Language{name: "Modula-2"},
  %Language{name: "Modula-3"},
  %Language{name: "Module Management System"},
  %Language{name: "Monkey"},
  %Language{name: "Moocode"},
  %Language{name: "MoonScript"},
  %Language{name: "MQL4"},
  %Language{name: "MQL5"},
  %Language{name: "MTML"},
  %Language{name: "MUF"},
  %Language{name: "mupad"},
  %Language{name: "Myghty"},
  %Language{name: "nanorc"},
  %Language{name: "NCL"},
  %Language{name: "Nearley"},
  %Language{name: "Nemerle"},
  %Language{name: "nesC"},
  %Language{name: "NetLinx"},
  %Language{name: "NetLinx+ERB"},
  %Language{name: "NetLogo"},
  %Language{name: "NewLisp"},
  %Language{name: "Nextflow"},
  %Language{name: "Nginx"},
  %Language{name: "Nim"},
  %Language{name: "Ninja"},
  %Language{name: "Nit"},
  %Language{name: "Nix"},
  %Language{name: "NL"},
  %Language{name: "NSIS"},
  %Language{name: "Nu"},
  %Language{name: "NumPy"},
  %Language{name: "ObjDump"},
  %Language{name: "Objective-C++"},
  %Language{name: "Objective-J"},
  %Language{name: "OCaml"},
  %Language{name: "Omgrofl"},
  %Language{name: "ooc"},
  %Language{name: "Opa"},
  %Language{name: "Opal"},
  %Language{name: "OpenCL"},
  %Language{name: "OpenEdge ABL"},
  %Language{name: "OpenRC runscript"},
  %Language{name: "OpenSCAD"},
  %Language{name: "OpenType Feature File"},
  %Language{name: "Org"},
  %Language{name: "Ox"},
  %Language{name: "Oxygene"},
  %Language{name: "Oz"},
  %Language{name: "P4"},
  %Language{name: "Pan"},
  %Language{name: "Papyrus"},
  %Language{name: "Parrot"},
  %Language{name: "Parrot Assembly"},
  %Language{name: "Parrot Internal Representation"},
  %Language{name: "Pascal"},
  %Language{name: "Pawn"},
  %Language{name: "Pep8"},
  %Language{name: "Perl 6"},
  %Language{name: "Pic"},
  %Language{name: "Pickle"},
  %Language{name: "PicoLisp"},
  %Language{name: "PigLatin"},
  %Language{name: "Pike"},
  %Language{name: "PLpgSQL"},
  %Language{name: "PLSQL"},
  %Language{name: "Pod"},
  %Language{name: "Pod 6"},
  %Language{name: "PogoScript"},
  %Language{name: "Pony"},
  %Language{name: "PostCSS"},
  %Language{name: "PostScript"},
  %Language{name: "POV-Ray SDL"},
  %Language{name: "PowerBuilder"},
  %Language{name: "PowerShell"},
  %Language{name: "Processing"},
  %Language{name: "Prolog"},
  %Language{name: "Propeller Spin"},
  %Language{name: "Protocol Buffer"},
  %Language{name: "Public Key"},
  %Language{name: "Pug"},
  %Language{name: "Puppet"},
  %Language{name: "Pure Data"},
  %Language{name: "PureBasic"},
  %Language{name: "PureScript"},
  %Language{name: "Python console"},
  %Language{name: "Python traceback"},
  %Language{name: "q"},
  %Language{name: "QMake"},
  %Language{name: "QML"},
  %Language{name: "Quake"},
  %Language{name: "Racket"},
  %Language{name: "Ragel"},
  %Language{name: "RAML"},
  %Language{name: "Rascal"},
  %Language{name: "Raw token data"},
  %Language{name: "RDoc"},
  %Language{name: "REALbasic"},
  %Language{name: "Reason"},
  %Language{name: "Rebol"},
  %Language{name: "Red"},
  %Language{name: "Redcode"},
  %Language{name: "Regular Expression"},
  %Language{name: "Ren'Py"},
  %Language{name: "RenderScript"},
  %Language{name: "reStructuredText"},
  %Language{name: "REXX"},
  %Language{name: "RHTML"},
  %Language{name: "Rich Text Format"},
  %Language{name: "Ring"},
  %Language{name: "RMarkdown"},
  %Language{name: "RobotFramework"},
  %Language{name: "Roff"},
  %Language{name: "Roff Manpage"},
  %Language{name: "Rouge"},
  %Language{name: "RPC"},
  %Language{name: "RPM Spec"},
  %Language{name: "RUNOFF"},
  %Language{name: "Rust"},
  %Language{name: "Sage"},
  %Language{name: "SaltStack"},
  %Language{name: "SAS"},
  %Language{name: "Sass"},
  %Language{name: "Scaml"},
  %Language{name: "Scheme"},
  %Language{name: "Scilab"},
  %Language{name: "SCSS"},
  %Language{name: "sed"},
  %Language{name: "Self"},
  %Language{name: "ShaderLab"},
  %Language{name: "ShellSession"},
  %Language{name: "Shen"},
  %Language{name: "Slash"},
  %Language{name: "Slice"},
  %Language{name: "Slim"},
  %Language{name: "Smali"},
  %Language{name: "Smalltalk"},
  %Language{name: "Smarty"},
  %Language{name: "SMT"},
  %Language{name: "Solidity"},
  %Language{name: "SourcePawn"},
  %Language{name: "SPARQL"},
  %Language{name: "Spline Font Database"},
  %Language{name: "SQF"},
  %Language{name: "SQL"},
  %Language{name: "SQLPL"},
  %Language{name: "Squirrel"},
  %Language{name: "SRecode Template"},
  %Language{name: "Stan"},
  %Language{name: "Standard ML"},
  %Language{name: "Stata"},
  %Language{name: "STON"},
  %Language{name: "Stylus"},
  %Language{name: "SubRip Text"},
  %Language{name: "SugarSS"},
  %Language{name: "SuperCollider"},
  %Language{name: "SVG"},
  %Language{name: "SystemVerilog"},
  %Language{name: "Tcl"},
  %Language{name: "Tcsh"},
  %Language{name: "Tea"},
  %Language{name: "Terra"},
  %Language{name: "Text"},
  %Language{name: "Textile"},
  %Language{name: "Thrift"},
  %Language{name: "TI Program"},
  %Language{name: "TLA"},
  %Language{name: "TOML"},
  %Language{name: "Turing"},
  %Language{name: "Turtle"},
  %Language{name: "Twig"},
  %Language{name: "TXL"},
  %Language{name: "Type Language"},
  %Language{name: "TypeScript"},
  %Language{name: "Unified Parallel C"},
  %Language{name: "Unity3D Asset"},
  %Language{name: "Unix Assembly"},
  %Language{name: "Uno"},
  %Language{name: "UnrealScript"},
  %Language{name: "UrWeb"},
  %Language{name: "Vala"},
  %Language{name: "VCL"},
  %Language{name: "Verilog"},
  %Language{name: "VHDL"},
  %Language{name: "Visual Basic"},
  %Language{name: "Volt"},
  %Language{name: "Vue"},
  %Language{name: "Wavefront Material"},
  %Language{name: "Wavefront Object"},
  %Language{name: "wdl"},
  %Language{name: "Web Ontology Language"},
  %Language{name: "WebAssembly"},
  %Language{name: "WebIDL"},
  %Language{name: "Windows Registry Entries"},
  %Language{name: "wisp"},
  %Language{name: "World of Warcraft Addon Data"},
  %Language{name: "X BitMap"},
  %Language{name: "X Font Directory Index"},
  %Language{name: "X PixMap"},
  %Language{name: "X10"},
  %Language{name: "xBase"},
  %Language{name: "XC"},
  %Language{name: "XCompose"},
  %Language{name: "XML"},
  %Language{name: "Xojo"},
  %Language{name: "XPages"},
  %Language{name: "XProc"},
  %Language{name: "XQuery"},
  %Language{name: "XS"},
  %Language{name: "XSLT"},
  %Language{name: "Xtend"},
  %Language{name: "Yacc"},
  %Language{name: "YAML"},
  %Language{name: "YANG"},
  %Language{name: "YARA"},
  %Language{name: "YASnippet"},
  %Language{name: "ZAP"},
  %Language{name: "Zephir"},
  %Language{name: "Zig"},
  %Language{name: "ZIL"},
  %Language{name: "Zimpl"}
]

Enum.each(languages, fn language -> Repo.insert!(language) end)
